--- #YAML:1.1
name:               IPTables-Parse
version:            1.1
abstract:           Perl extension for parsing iptables and ip6tables firewall rulesets
author:
    - Michael Rash <mbr@cipherdyne.org>
license:            Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
