--- #YAML:1.0
name:               IPTables-ChainMgr
version:            1.2
abstract:           Perl extension for manipulating iptables and ip6tables policies
author:
    - Michael Rash <mbr@cipherdyne.org>
license:            Artistic
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IPTables::Parse:  0.9
    NetAddr::IP:      4
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
